## Request timeout
# timeout: 5s

## Uncomment following line in order to write template from scratch (be careful!)
#no_builtin_template: true

## Customizable templates path
#templates:
#  - contrib/templates/legacy/template.tmpl
templates:
   - /usr/local/prometheus-webhook-dingtalk/contrib/templates/bsy/template.tmpl
## You can also override default template using `default_message`
## The following example to use the 'legacy' template from v0.3.0
#default_message:
#  title: '{{ template "legacy.title" . }}'
#  text: '{{ template "legacy.content" . }}'

## Targets, previously was known as "profiles"
targets:
  webhook:
    #url: https://oapi.dingtalk.com/robot/send?access_token=17a3d50bb43af0c4776057ac8f9aab8ca2fdb1c334e4e72d8f3778378e53ba90
    url: https://oapi.dingtalk.com/robot/send?access_token=0b8a9f9f418a69ea2ddc93342a0a1a13b96741b807b52e3370e5cdf3921643d0
    # secret for signature
    message:
      title: '{{ template "ding.link.title" . }}'
      text: '{{ template "ding.link.content" . }}'
