# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"
  #- "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'kubernetes-pods'
    scheme: https
    kubernetes_sd_configs:
    - api_server: https://172.16.2.52:6443
      role: pod
      bearer_token_file: k8s.token
      tls_config:
        insecure_skip_verify: true
    bearer_token_file: k8s.token
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_kafka]
      action: keep
      regex: true
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_kport]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'bsy-monitor'
    static_configs:
    - targets: ['172.16.2.208:9100']

  - job_name: 'bsy-kafka-export'
    static_configs:
    - targets: ['172.16.2.56:30106']

  - job_name: 'bsy-es-export'
    static_configs:
    - targets: ['172.16.2.56:31985']

  - job_name: 'bsy-kafajvm-export'
    static_configs:
    - targets: ['172.16.2.208:9997']

  - job_name: 'bsy-jenkins_process'
    static_configs:
    - targets: ['bsy-jenkins-master:9256','bsy-jenkins-agent-1:9256','bsy-jenkins-agent-2:9256']
  - job_name: 'bsy-jenkins-master_jenkins'
    metrics_path: '/prometheus'
    static_configs:
    - targets: ['bsy-jenkins-master:8080']
  - job_name: 'bsy-jenkins_node'
    static_configs:
    - targets: ['bsy-jenkins-master:9100','bsy-jenkins-agent-1:9100','bsy-jenkins-agent-2:9100']

  - job_name: 'bsy-rabbitmq_mq'
    static_configs:
    - targets: ['bsy-rabbitmq-1:15692','bsy-rabbitmq-2:15692','172.16.2.60:15692','172.16.2.61:15692']
  - job_name: 'bsy-rabbitmq_node'
    static_configs:
    - targets: ['bsy-rabbitmq-1:9100','bsy-rabbitmq-2:9100','172.16.2.60:9100','172.16.2.61:9100']

  - job_name: 'php-template_node'
    static_configs:
    - targets: ['php-template:9100']
  - job_name: 'php-template_process'
    static_configs:
    - targets: ['php-template:9256']
  
  - job_name: bsy-nacos-1
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
    - targets: ['172.16.2.204:8848']
  - job_name: bsy-nacos-2
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
    - targets: ['172.16.2.205:8848']
  - job_name: bsy-nacos-3
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
    - targets: ['172.16.2.206:8848']

  - job_name: 'gatewayaccess'
    metrics_path: /metrics
    static_configs:
    - targets: ['172.16.2.190:8001','172.16.2.195:8001']
  
  - job_name: 'bsy-api-im_process'
    static_configs:
    - targets: ['bsy-api-im-1:9256','bsy-api-im-2:9256']
  - job_name: 'bsy-api-puc_process'
    static_configs:
    - targets: ['bsy-api-puc-1:9256','bsy-api-puc-2:9256']
  - job_name: 'bsy-api-sc_process'
    static_configs:
    - targets: ['bsy-api-sc-1:9256','bsy-api-sc-2:9256']
  - job_name: 'bsy-api-imapp_process'
    static_configs:
    - targets: ['bsy-api-imapp-1:9256','bsy-api-imapp-2:9256','bsy-api-crontab:9256']
  - job_name: 'bsy-api-oc_process'
    static_configs:
    - targets: ['bsy-api-oc-1:9256','bsy-api-oc-2:9256']
  - job_name: 'bsy-api-learn_process'
    static_configs:
    - targets: ['bsy-api-learn-1:9256','bsy-api-learn-2:9256']



  - job_name: 'bsy-live_process'
    static_configs:
    - targets: ['bsy-live-platform-1:9256','bsy-live-platform-2:9256','bsy-live-platform-3:9256','bsy-live-platform-4:9256']
  - job_name: 'bsy-base_process'
    static_configs:
    - targets: ['bsy-base-1:9256','bsy-base-2:9256']
  - job_name: 'bsy-mall_process'
    static_configs:
    - targets: ['bsy-mall-1:9256','bsy-mall-2:9256']
  - job_name: 'bsy-report-center_process'
    static_configs:
    - targets: ['bsy-live-report-center-1:9256','bsy-live-report-center-2:9256']
  - job_name: 'bsy-live-virtual_process'
    static_configs:
    - targets: ['bsy-live-virtual-1:9256','bsy-live-virtual-2:9256','bsy-live-virtual-3:9256']
  - job_name: 'bsy-pingce_process'
    static_configs:
    - targets: ['bsy-pingce-1:9256','bsy-pingce-2:9256']
 
  - job_name: 'bsy-golang'
    static_configs:
    - targets: ['172.16.2.25:9256','172.16.2.26:9256']
  - job_name: 'bsy-es-kafka'
    static_configs:
    - targets: ['172.16.2.214:9256','172.16.2.215:9256','172.16.2.213:9256','172.16.2.37:9256','172.16.2.38:9256','172.16.2.39:9256','172.16.2.218:9256','172.16.2.219:9256','172.16.2.220:9256']
  - job_name: 'bsy-base-service-proxy_status'
    metrics_path: '/status/format/prometheus'
    static_configs:
    - targets: ['bsy-proxy-1:8081', 'bsy-proxy-2:8081']
      labels:
        app: BSY-PROXY-NGINX

  - job_name: 'bsy-base-service_process'
    file_sd_configs:
      - files: ['/usr/local/prometheus/targets/bsy-base-service_process.yml']
        refresh_interval: 5s

  - job_name: 'bsy-app-service_port'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files: ['/usr/local/prometheus/targets/bsy-app-service_port.yml']
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'bsy-base-service_port'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files: ['/usr/local/prometheus/targets/bsy-base-service_port.yml']
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'bsy-app-server_node'
    file_sd_configs:
      - files: ['/usr/local/prometheus/targets/bsy-server_node.yml']
        refresh_interval: 5s
