groups:
- name: kafkaex-StatsAlert
  rules:
  - alert: es内存超过百分之90
    expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 0.9
    for: 30s
    labels:
      severity: 严重
    annotations:
      description: "主机名称：{{ $labels.name }}"
